version: "3.8"
services: 
  auth-ms:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    ports:
      - 1018:1018
    env_file:
      - ./apps/auth-service/.env
    # depends_on:
    #   - auth-srv-db
  restaurant-ms:
    build:
      context: .
      dockerfile: ./apps/restaurant-service/Dockerfile
    ports:
      - 1019:1019
    env_file:  # although every var in the .env file is loaded into this service, but the service will only use what it requires or references
      - ./apps/restaurant-service/.env
    depends_on:
      - restaurant-srv-db
  restaurant-srv-db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./apps/restaurant-service/.env
    # environment: # whatever is specified here will be loaded into this services env
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_DB=restaurant-pg-db
    volumes:
      - restaurant-srv-db:/var/lib/postgresql/data
volumes:
  restaurant-srv-db:
    
    